"""création de la table user

Revision ID: 0b0898bf3dfc
Revises: 
Create Date: 2023-12-05 19:18:33.693525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0898bf3dfc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('idUser', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('idUser'),
    sa.UniqueConstraint('idUser')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
